In [37]:
# Data provided by Redfin, a national real estate brokerage
import pandas as pd

In [38]:
# Store filepath in a variable
raw_data = "Resources/weekly_housing_market_rawdata_10.10.2020.csv"

# Read our Data file with the pandas library
raw_data_df = pd.read_csv(raw_data, encoding="utf-8")
raw_data_df.head()

/Users/lmm/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (4,5,77) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,region_id,region_type_id,region_name,region_type,period_begin,period_end,duration,total_homes_sold,total_homes_sold_yoy,average_homes_sold,...,median_days_on_market_yoy,pending_sales_to_sales_ratio,pending_sales_to_sales_ratio_yoy,months_of_supply,months_of_supply_yoy,average_pending_sales_listing_updates,average_pending_sales_listing_updates_yoy,percent_total_price_drops_of_inventory,percent_total_price_drops_of_inventory_yoy,last_updated
0,525.0,5.0,"Carroll County, GA",county,1/8/18,1/14/18,1 weeks,19.0,0.187500,19.0,...,-20.0,NaN,NaN,20.000000,-7.250000,40.0,0.481481,0.048851,0.007488,9/30/20 14:35
1,525.0,5.0,"Carroll County, GA",county,1/29/18,2/4/18,1 weeks,30.0,0.363636,30.0,...,23.5,NaN,NaN,12.300000,-7.381818,53.0,0.261905,0.028037,0.000330,9/30/20 14:35
2,525.0,5.0,"Carroll County, GA",county,6/29/20,7/5/20,1 weeks,46.0,1.190476,46.0,...,-19.0,NaN,NaN,8.152174,-10.943064,53.0,0.358974,0.039275,0.000601,9/30/20 14:35
3,267.0,5.0,"Lincoln County, AR",county,2/19/18,2/25/18,1 weeks,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166667,-0.033333,9/30/20 14:35
4,3215.0,5.0,"Richland County, WI",county,6/1/20,6/7/20,1 weeks,1.0,-0.666667,1.0,...,-79.0,NaN,NaN,55.000000,27.000000,3.0,-0.500000,0.018868,-0.018632,9/30/20 14:35

In [39]:
# Show just the header
len(raw_data_df)

918835

In [47]:
raw_data_df.columns

Index(['region_id', 'region_type_id', 'region_name', 'region_type',
       'period_begin', 'period_end', 'duration', 'total_homes_sold',
       'total_homes_sold_yoy', 'average_homes_sold', 'average_homes_sold_yoy',
       'total_homes_sold_with_price_drops',
       'total_homes_sold_with_price_drops_yoy',
       'average_homes_sold_with_price_drops',
       'average_homes_sold_with_price_drops_yoy',
       'percent_homes_sold_with_price_drops',
       'percent_homes_sold_with_price_drops_yoy', 'median_sale_price',
       'median_sale_price_yoy', 'median_sale_ppsf', 'median_sale_ppsf_yoy',
       'median_days_to_close', 'median_days_to_close_yoy', 'price_drops',
       'price_drops_yoy', 'percent_active_listings_with_price_drops',
       'percent_active_listings_with_price_drops_yoy', 'pending_sales',
       'pending_sales_yoy', 'median_pending_sqft', 'median_pending_sqft_yoy',
       'off_market_in_two_weeks', 'off_market_in_two_weeks_yoy',
       'percent_off_market_in_two_weeks',
       'percent_off_market_in_two_weeks_yoy', 'total_new_listings',
       'total_new_listings_yoy', 'average_new_listings',
       'average_new_listings_yoy', 'median_new_listing_price',
       'median_new_listing_price_yoy', 'median_new_listing_ppsf',
       'median_new_listing_ppsf_yoy', 'inventory', 'inventory_yoy',
       'total_active_listings', 'total_active_listings_yoy', 'active_listings',
       'active_listings_yoy', 'age_of_inventory', 'age_of_inventory_yoy',
       'homes_delisted', 'homes_delisted_yoy',
       'percent_active_listings_delisted',
       'percent_active_listings_delisted_yoy', 'median_active_list_price',
       'median_active_list_price_yoy', 'median_active_list_ppsf',
       'median_active_list_ppsf_yoy', 'average_of_median_list_price_amount',
       'average_of_median_list_price_amount_yoy',
       'average_of_median_offer_price_amount',
       'average_of_median_offer_price_amount_yoy', 'avg_offer_to_list',
       'avg_offer_to_list_yoy', 'average_sale_to_list_ratio',
       'average_sale_to_list_ratio_yoy', 'median_days_on_market',
       'median_days_on_market_yoy', 'pending_sales_to_sales_ratio',
       'pending_sales_to_sales_ratio_yoy', 'months_of_supply',
       'months_of_supply_yoy', 'average_pending_sales_listing_updates',
       'average_pending_sales_listing_updates_yoy',
       'percent_total_price_drops_of_inventory',
       'percent_total_price_drops_of_inventory_yoy', 'last_updated'],
      dtype='object')

In [58]:
columns1=[
    "region_name", 
    "region_type", 
    "period_begin", 
    "period_end",
    "total_homes_sold", 
    "total_new_listings", 
    "total_active_listings",
    "price_drops",
    "homes_delisted",
    "median_sale_price",
    "median_days_on_market",
    "months_of_supply",
    "age_of_inventory"]

weekly_df=raw_data_df.loc[raw_data_df["duration"] == "1 weeks",columns1]
weekly_df.head()

,region_name,region_type,period_begin,period_end,total_homes_sold,total_new_listings,total_active_listings,price_drops,homes_delisted,median_sale_price,median_days_on_market,months_of_supply,age_of_inventory
0,"Carroll County, GA",county,1/8/18,1/14/18,19.0,25.0,380.0,17.0,NaN,129900.0,28.0,20.000000,73.0
1,"Carroll County, GA",county,1/29/18,2/4/18,30.0,44.0,369.0,9.0,NaN,161100.0,80.5,12.300000,74.0
2,"Carroll County, GA",county,6/29/20,7/5/20,46.0,48.0,375.0,13.0,NaN,194700.0,23.0,8.152174,50.0
3,"Lincoln County, AR",county,2/19/18,2/25/18,NaN,NaN,6.0,1.0,NaN,NaN,NaN,NaN,130.0
4,"Richland County, WI",county,6/1/20,6/7/20,1.0,3.0,55.0,1.0,2.0,45000.0,43.0,55.000000,90.0

In [59]:
len(weekly_df)

313531

In [60]:
weekly_df.dtypes

region_name               object
region_type               object
period_begin              object
period_end                object
total_homes_sold         float64
total_new_listings       float64
total_active_listings    float64
price_drops              float64
homes_delisted           float64
median_sale_price        float64
median_days_on_market    float64
months_of_supply         float64
age_of_inventory         float64
dtype: object

In [80]:
#start a new DataFrame to cleanup
clean_df=weekly_df

#break out period_begin into month, day, year
clean_df[['month','day','year']] = clean_df.period_begin.str.split("/",expand=True)

#add leading 20 to year
clean_df['year'] ='20' + clean_df['year']

#replace month number with month name
clean_df['month']=clean_df['month'].replace(
{'1':'January',
'2':'February',
'3':'March',
'4':'April',
'5':'May',
'6':'June',
'7':'July',
'8':'August',
'9':'September',
'10':'October',
'11':'November',
'12':'December'})

#merge month and year for grouping
clean_df['month_year'] =clean_df['month'].astype(str) + " "+ clean_df['year']
clean_df.head()

,region_name,region_type,period_begin,period_end,total_homes_sold,total_new_listings,total_active_listings,price_drops,homes_delisted,median_sale_price,median_days_on_market,months_of_supply,age_of_inventory,month,day,year,region,state,month_year
0,"Carroll County, GA",county,1/8/18,1/14/18,19.0,25.0,380.0,17.0,NaN,129900.0,28.0,20.000000,73.0,January,8,2018,Carroll County,GA,January 2018
1,"Carroll County, GA",county,1/29/18,2/4/18,30.0,44.0,369.0,9.0,NaN,161100.0,80.5,12.300000,74.0,January,29,2018,Carroll County,GA,January 2018
2,"Carroll County, GA",county,6/29/20,7/5/20,46.0,48.0,375.0,13.0,NaN,194700.0,23.0,8.152174,50.0,June,29,2020,Carroll County,GA,June 2020
3,"Lincoln County, AR",county,2/19/18,2/25/18,NaN,NaN,6.0,1.0,NaN,NaN,NaN,NaN,130.0,February,19,2018,Lincoln County,AR,February 2018
4,"Richland County, WI",county,6/1/20,6/7/20,1.0,3.0,55.0,1.0,2.0,45000.0,43.0,55.000000,90.0,June,1,2020,Richland County,WI,June 2020

In [65]:
#break out region_name into city, and state
clean_df[['region','state']] = clean_df.region_name.str.split(", ",expand=True)

#only take first two characters of state
clean_df['state'] = clean_df['state'].str[:2]
clean_df.head()

,region_name,region_type,period_begin,period_end,total_homes_sold,total_new_listings,total_active_listings,price_drops,homes_delisted,median_sale_price,median_days_on_market,months_of_supply,age_of_inventory,month,day,year,region,state
0,"Carroll County, GA",county,1/8/18,1/14/18,19.0,25.0,380.0,17.0,NaN,129900.0,28.0,20.000000,73.0,1,8,2018,Carroll County,GA
1,"Carroll County, GA",county,1/29/18,2/4/18,30.0,44.0,369.0,9.0,NaN,161100.0,80.5,12.300000,74.0,1,29,2018,Carroll County,GA
2,"Carroll County, GA",county,6/29/20,7/5/20,46.0,48.0,375.0,13.0,NaN,194700.0,23.0,8.152174,50.0,6,29,2020,Carroll County,GA
3,"Lincoln County, AR",county,2/19/18,2/25/18,NaN,NaN,6.0,1.0,NaN,NaN,NaN,NaN,130.0,2,19,2018,Lincoln County,AR
4,"Richland County, WI",county,6/1/20,6/7/20,1.0,3.0,55.0,1.0,2.0,45000.0,43.0,55.000000,90.0,6,1,2020,Richland County,WI

In [77]:
clean_df.year.value_counts()

2018    83486
2019    82038
2017    81754
2020    59767
Name: year, dtype: int64